### ISSUE TITLE
Exception while migrating Silicon

### ISSUE THREAD

**Issue by fpoli** [viperproject/bitbucket-issue-migration#14]
Exception while migrating Silicon:
```
Migrate attachments for bitbucket issue #208... [rate limiting: 3633]
Traceback (most recent call last):
  File "./migrate-discussions.py", line 872, in <module>
    main()
  File "./migrate-discussions.py", line 868, in main
    bitbucket_to_github(bexport=bexport, gimport=gimport, cmap=cmap, args=args)
  File "./migrate-discussions.py", line 686, in bitbucket_to_github
    gist = gimport.get_or_create_gist_by_description(gist_data)
  File "/home/fpoli/src/bitbucket-issue-migration/src/github.py", line 54, in get_or_create_gist_by_description
    gist_data["description"]
  File "/home/fpoli/.local/lib/python3.5/site-packages/github/AuthenticatedUser.py", line 532, in create_gist
    "POST", "/gists", input=post_parameters
  File "/home/fpoli/.local/lib/python3.5/site-packages/github/Requester.py", line 322, in requestJsonAndCheck
    verb, url, parameters, headers, input, self.__customConnection(url)
  File "/home/fpoli/.local/lib/python3.5/site-packages/github/Requester.py", line 345, in __check
    raise self.__createException(status, responseHeaders, output)
github.GithubException.GithubException: 502 {"message": "Server Error"}
```

**Comment by fpoli** [comment]
Again:
```
Migrate attachments for bitbucket issue #208... [rate limiting: 3527]
Traceback (most recent call last):
  File "./migrate-discussions.py", line 876, in <module>
    main()
  File "./migrate-discussions.py", line 872, in main
    bitbucket_to_github(bexport=bexport, gimport=gimport, cmap=cmap, args=args)
  File "./migrate-discussions.py", line 686, in bitbucket_to_github
    gist = gimport.get_or_create_gist_by_description(gist_data)
  File "/home/fpoli/src/bitbucket-issue-migration/src/github.py", line 57, in get_or_create_gist_by_description
    gist.edit(gist_data["description"], gist_data["files"])
  File "/home/fpoli/.local/lib/python3.5/site-packages/github/Gist.py", line 265, in edit
    "PATCH", self.url, input=post_parameters
  File "/home/fpoli/.local/lib/python3.5/site-packages/github/Requester.py", line 322, in requestJsonAndCheck
    verb, url, parameters, headers, input, self.__customConnection(url)
  File "/home/fpoli/.local/lib/python3.5/site-packages/github/Requester.py", line 345, in __check
    raise self.__createException(status, responseHeaders, output)
github.GithubException.GithubException: 502 {"message": "Server Error"}
```

This seems deterministic.

**Comment by fpoli** [comment]
Again:
```
Migrate attachments for bitbucket issue #208... [rate limiting: 4818]
Traceback (most recent call last):
  File "./migrate-discussions.py", line 876, in <module>
    main()
  File "./migrate-discussions.py", line 872, in main
    bitbucket_to_github(bexport=bexport, gimport=gimport, cmap=cmap, args=args)
  File "./migrate-discussions.py", line 686, in bitbucket_to_github
    gist = gimport.get_or_create_gist_by_description(gist_data)
  File "/home/fpoli/src/bitbucket-issue-migration/src/github.py", line 57, in get_or_create_gist_by_description
    gist.edit(gist_data["description"], gist_data["files"])
  File "/home/fpoli/.local/lib/python3.5/site-packages/github/Gist.py", line 265, in edit
    "PATCH", self.url, input=post_parameters
  File "/home/fpoli/.local/lib/python3.5/site-packages/github/Requester.py", line 322, in requestJsonAndCheck
    verb, url, parameters, headers, input, self.__customConnection(url)
  File "/home/fpoli/.local/lib/python3.5/site-packages/github/Requester.py", line 345, in __check
    raise self.__createException(status, responseHeaders, output)
github.GithubException.GithubException: 502 {"message": "Server Error"}
```

Maybe it's due to a big file attachment (16MB).

**Comment by fpoli** [comment]
Indeed:
> The Gist API provides up to one megabyte of content for each file in the gist.
(https://developer.github.com/v3/gists/#truncation)

**Comment by fpoli** [comment]
Solved: big attachments can only be uploaded manually
