### ISSUE TITLE
Validation Failed Github Exception

### ISSUE THREAD

**Issue by fpoli** [viperproject/bitbucket-issue-migration#16]
Exception while migrating Silicon:
```
Migrate attachments for bitbucket issue #335... [rate limiting: 4595]
Traceback (most recent call last):
  File "./migrate-discussions.py", line 883, in <module>
    main()
  File "./migrate-discussions.py", line 879, in main
    bitbucket_to_github(bexport=bexport, gimport=gimport, cmap=cmap, args=args)
  File "./migrate-discussions.py", line 693, in bitbucket_to_github
    gist = gimport.get_or_create_gist_by_description(gist_data)
  File "/home/fpoli/src/bitbucket-issue-migration/src/github.py", line 54, in get_or_create_gist_by_description
    gist_data["description"]
  File "/home/fpoli/.local/lib/python3.5/site-packages/github/AuthenticatedUser.py", line 532, in create_gist
    "POST", "/gists", input=post_parameters
  File "/home/fpoli/.local/lib/python3.5/site-packages/github/Requester.py", line 322, in requestJsonAndCheck
    verb, url, parameters, headers, input, self.__customConnection(url)
  File "/home/fpoli/.local/lib/python3.5/site-packages/github/Requester.py", line 345, in __check
    raise self.__createException(status, responseHeaders, output)
github.GithubException.GithubException: 422 {"message": "Validation Failed", "documentation_url": "https://developer.github.com/v3/gists/#create-a-gist", "errors": [{"field": "files", "resource": "Gist", "code": "missing_field"}]}
```

**Comment by fpoli** [comment]
This seems deterministic. Content of the `files` dictionary:
```
{
  '# README.md': <github.InputFileContent.InputFileContent object at 0x7f9abb69e2e8>,
  'silicon-assertion-failed-b.vpr': <github.InputFileContent.InputFileContent object at 0x7f9abb692dd8>,
  'silicon-assertion-failed-a.vpr': <github.InputFileContent.InputFileContent object at 0x7f9abb70dcc0>
}
```

**Comment by fpoli** [comment]
Maybe it's because the attachments were empty.

**Comment by fpoli** [comment]
Solved
