### ISSUE TITLE
Invalid pull request creation

### ISSUE THREAD

**Issue by fpoli** [viperproject/bitbucket-issue-migration#20]
From the migration:
```
Upload github issue or pull request #469... [rate limiting: 4078]
Create github pull request #469...
Traceback (most recent call last):
  File "./migrate-discussions.py", line 890, in <module>
    main()
  File "./migrate-discussions.py", line 886, in main
    bitbucket_to_github(bexport=bexport, gimport=gimport, cmap=cmap, args=args)
  File "./migrate-discussions.py", line 749, in bitbucket_to_github
    gimport.create_pull_with_comments(data)
  File "/home/fpoli/src/bitbucket-issue-migration/src/github.py", line 185, in create_pull_with_comments
    head=meta["head"],
  File "/home/fpoli/.local/lib/python3.5/site-packages/github/Repository.py", line 1307, in create_pull
    return self.__create_pull_1(*args, **kwds)
  File "/home/fpoli/.local/lib/python3.5/site-packages/github/Repository.py", line 1330, in __create_pull_1
    return self.__create_pull(title=title, body=body, base=base, head=head)
  File "/home/fpoli/.local/lib/python3.5/site-packages/github/Repository.py", line 1341, in __create_pull
    "POST", self.url + "/pulls", input=post_parameters
  File "/home/fpoli/.local/lib/python3.5/site-packages/github/Requester.py", line 322, in requestJsonAndCheck
    verb, url, parameters, headers, input, self.__customConnection(url)
  File "/home/fpoli/.local/lib/python3.5/site-packages/github/Requester.py", line 345, in __check
    raise self.__createException(status, responseHeaders, output)
github.GithubException.GithubException: 422 {"documentation_url": "https://developer.github.com/v3/pulls/#create-a-pull-request", "errors": [{"resource": "PullRequest", "field": "head", "code": "invalid"}], "message": "Validation Failed"}
```

**Comment by fpoli** [comment]
Again:
```
Upload github issue or pull request #472... [rate limiting: 3601]
Create github pull request #472...
Traceback (most recent call last):
  File "./migrate-discussions.py", line 910, in <module>
    main()
  File "./migrate-discussions.py", line 906, in main
    bitbucket_to_github(bexport=bexport, gimport=gimport, cmap=cmap, args=args)
  File "./migrate-discussions.py", line 769, in bitbucket_to_github
    gimport.create_pull_with_comments(data)
  File "/home/fpoli/src/bitbucket-issue-migration/src/github.py", line 185, in create_pull_with_comments
    head=meta["head"],
  File "/home/fpoli/.local/lib/python3.5/site-packages/github/Repository.py", line 1307, in create_pull
    return self.__create_pull_1(*args, **kwds)
  File "/home/fpoli/.local/lib/python3.5/site-packages/github/Repository.py", line 1330, in __create_pull_1
    return self.__create_pull(title=title, body=body, base=base, head=head)
  File "/home/fpoli/.local/lib/python3.5/site-packages/github/Repository.py", line 1341, in __create_pull
    "POST", self.url + "/pulls", input=post_parameters
  File "/home/fpoli/.local/lib/python3.5/site-packages/github/Requester.py", line 322, in requestJsonAndCheck
    verb, url, parameters, headers, input, self.__customConnection(url)
  File "/home/fpoli/.local/lib/python3.5/site-packages/github/Requester.py", line 345, in __check
    raise self.__createException(status, responseHeaders, output)
github.GithubException.GithubException: 422 {"message": "Validation Failed", "documentation_url": "https://developer.github.com/v3/pulls/#create-a-pull-request", "errors": [{"code": "invalid", "field": "head", "resource": "PullRequest"}]}
```

**Comment by fpoli** [comment]
It's because of
```
commit 8ece9dbc0928 of fork maurobringolf/silicon does not exist => skipped
```
which causes
```
Warning: could not map mercurial commit '8ece9dbc0928' (source of a PR) to git.
```
and thus tries to create an open PR with a None source (head) commit,

**Comment by fpoli** [comment]
Fixed
