### ISSUE TITLE
TypeError: Can't convert 'int' object to str implicitly

### ISSUE THREAD

**Issue by fpoli** [viperproject/bitbucket-issue-migration#28]
```
Migrate attachments for bitbucket issue #409... [rate limiting: 3102]
Prepare github issues...
Prepare github issue #1 from bitbucket issue...
Prepare github issue #2 from bitbucket issue...
Prepare github issue #3 from bitbucket issue...
Prepare github issue #4 from bitbucket issue...
Prepare github issue #5 from bitbucket issue...
Prepare github issue #6 from bitbucket issue...
Prepare github issue #7 from bitbucket issue...
Prepare github issue #8 from bitbucket issue...
Traceback (most recent call last):
  File "./migrate-discussions.py", line 951, in <module>
    main()
  File "./migrate-discussions.py", line 947, in main
    bitbucket_to_github(bexport=bexport, gimport=gimport, cmap=cmap, args=args)
  File "./migrate-discussions.py", line 767, in bitbucket_to_github
    gissue = construct_gissue_from_bissue(bissue, bexport, attachment_gist_by_issue_id, cmap, args)
  File "./migrate-discussions.py", line 611, in construct_gissue_from_bissue
    comments += construct_gissue_comments(bcomments, cmap, args)
  File "./migrate-discussions.py", line 519, in construct_gissue_comments
    "body": construct_gcomment_body(bcomment, bcomments, cmap, args),
  File "./migrate-discussions.py", line 322, in construct_gcomment_body
    sb.append("" if bcomment["content"]["raw"] is None else map_content(bcomment["content"]["raw"], cmap, args))
  File "./migrate-discussions.py", line 253, in map_content
    tmp = replace_implicit_links_to_prs(tmp, args)
  File "./migrate-discussions.py", line 109, in replace_implicit_links_to_prs
    return IMPLICIT_PR_LINK_RE.sub(replace_pr_link, body)
  File "./migrate-discussions.py", line 106, in replace_pr_link
    gpr_number = bpr_nr + issues_count
TypeError: Can't convert 'int' object to str implicitly
```

**Comment by ArquintL** [comment]
Fixed in 07025e5
