### ISSUE TITLE
The script crashes when there's no issue tracker

### ISSUE THREAD

**Issue by fabiopakk** [viperproject/bitbucket-issue-migration#31]
Whenever attempting to port a repository from BitBucket which contains no issue tracker, the script runs into an exception:

```
Traceback (most recent call last):
  File "./migrate-discussions.py", line 1007, in <module>
    main()
  File "./migrate-discussions.py", line 1003, in main
    bitbucket_to_github(bexport=bexport, gimport=gimport, cmap=cmap, args=args)
  File "./migrate-discussions.py", line 794, in bitbucket_to_github
    bissues = bexport.get_issues()
  File "/home/pakk/migration/bitbucket-issue-migration/src/bitbucket.py", line 43, in get_issues
    issues = list(get_paginated_json(self.repo_url + "/issues", self.session))
  File "/home/pakk/migration/bitbucket-issue-migration/src/bitbucket.py", line 12, in get_paginated_json
    result = get_request_json(next_url, session)
  File "/home/pakk/migration/bitbucket-issue-migration/src/utils.py", line 18, in get_request_json
    res.raise_for_status()
  File "/home/pakk/.local/lib/python3.5/site-packages/requests/models.py", line 941, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://api.bitbucket.org/2.0/repositories/viperproject/documentation/issues
Traceback (most recent call last):
  File "main.py", line 209, in <module>
    main()
  File "main.py", line 205, in main
    ), cwd=ROOT)
  File "main.py", line 27, in execute
    check_call(cmd, *args, shell=True, **kwargs)
  File "/usr/lib/python3.5/subprocess.py", line 271, in check_call
    raise CalledProcessError(retcode, cmd)
```

**Comment by fabiopakk** [comment]
Fixed this issue and committed solution into master branch.
