### ISSUE TITLE
Port script is unable to handle wrong date

### ISSUE THREAD

**Issue by fabiopakk** [viperproject/bitbucket-issue-migration#38]
Some of the repositories have wrong date into their commits, which causes the exception bellow:

```
fatal: Invalid raw date "<devnull@localhost> 1439739323 +0200" in ident:  <> <devnull@localhost> 1439739323 +0200
fast-import: dumping crash report to .git/fast_import_crash_2931
Traceback (most recent call last):
  File "/home/pakk/migration/fast-export/hg-fast-export.py", line 529, in <module>
    notes=options.notes,encoding=encoding,fn_encoding=fn_encoding))
  File "/home/pakk/migration/fast-export/hg-fast-export.py", line 427, in hg2git
    sob,brmap,hgtags,encoding,fn_encoding)
  File "/home/pakk/migration/fast-export/hg-fast-export.py", line 248, in export_commit
    export_file_contents(ctx,man,added,hgtags,fn_encoding)
  File "/home/pakk/migration/fast-export/hg-fast-export.py", line 139, in export_file_contents
    strip_leading_slash(filename)))
  File "/home/pakk/migration/fast-export/hg-fast-export.py", line 37, in wr
    wr_no_nl(msg)
  File "/home/pakk/migration/fast-export/hg-fast-export.py", line 34, in wr_no_nl
    sys.stdout.write(msg)
IOError: [Errno 32] Broken pipe
```

This issues must be fixed in order to properly port all the repositories to GitHub.

**Comment by fpoli** [comment]
See this: https://github.com/frej/fast-export/issues/184

**Comment by fpoli** [comment]
From the issue, it seems that adding `"<>"="Unknown author <devnull@localhost>"` to `migration_data/authors.map` should be enough.

**Comment by fabiopakk** [comment]
Thanks for the hint, @fpoli . Issue fixed.
