### ISSUE TITLE
Porting script is crashing while processing pull requests on private repositories

### ISSUE THREAD

**Issue by fabiopakk** [viperproject/bitbucket-issue-migration#42]
The stack trace is:

```
Prepare github issue #116 from bitbucket pull request...
Traceback (most recent call last):
  File "./migrate-discussions.py", line 1020, in <module>
    main()
  File "./migrate-discussions.py", line 1016, in main
    bitbucket_to_github(bexport=bexport, gimport=gimport, cmap=cmap, args=args)
  File "./migrate-discussions.py", line 836, in bitbucket_to_github
    gissue_or_gpull = construct_gissue_or_gpull_from_bpull(bpull, bexport, cmap, args)
  File "./migrate-discussions.py", line 702, in construct_gissue_or_gpull_from_bpull
    comments += construct_gissue_comments(bcomments, cmap, args, bexport)
  File "./migrate-discussions.py", line 575, in construct_gissue_comments
    "body": construct_gcomment_body(bcomment, bcomments, cmap, args, bexport),
  File "./migrate-discussions.py", line 299, in construct_gcomment_body
    bcomment = bexport.get_detailed_comment(bcomment)
  File "/home/pakk/migration/bitbucket-issue-migration/src/bitbucket.py", line 98, in get_detailed_comment
    return get_request_json(shallow_comment["links"]["self"]["href"])
  File "/home/pakk/migration/bitbucket-issue-migration/src/utils.py", line 18, in get_request_json
    res.raise_for_status()
  File "/home/pakk/.local/lib/python3.5/site-packages/requests/models.py", line 941, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 403 Client Error: Forbidden for url: https://api.bitbucket.org/2.0/repositories/viperproject/voila/pullrequests/9/comments/70146327
```

**Comment by fabiopakk** [comment]
This issue was caused by "unavailable comments". The code is now handling this particular case.
